# Generated by Django 5.0.1 on 2024-03-10 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Clients', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='total_fees',
        ),
    ]
