# Generated by Django 5.0.1 on 2024-03-10 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='total_fees',
            field=models.IntegerField(),
        ),
    ]
