# Generated by Django 5.0.1 on 2024-03-10 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clients', '0002_alter_member_total_fees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='amount',
            field=models.IntegerField(),
        ),
    ]
